def findTheDifference(s, t):
	dict = {}
	
	for ele in s:
		if ele in dict:
			dict[ele] += 1
		else:
			dict[ele] = 1
	
	print(f"dict: {dict}")
	
	for ele in t:
		if ele in dict and dict[ele] > 0:
			dict[ele] -= 1
			#print(f"Updating dict: ")
		else:
			return ele
	
	
if __name__ == "__main__":
	s = "a"
	t = "aa"
	print(findTheDifference(s,t))
	
#You are given two strings s and t.

#String t is generated by random shuffling string s and then add one more letter at a random position.

#Return the letter that was added to t.

#Example 1:

#Input: s = "abcd", t = "abcde"
#Output: "e"
#Explanation: 'e' is the letter that was added.
#Example 2:

#Input: s = "", t = "y"
#Output: "y"
#Example 3:

#Input: s = "a", t = "aa"
#Output: "a"
#Example 4:

#Input: s = "ae", t = "aea"
#Output: "a"